// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"ink-im-server/internal/repository/dao"
	"ink-im-server/internal/repository/user_repo"
	"ink-im-server/internal/service/user_service"
	"ink-im-server/internal/web/user_web"
	"ink-im-server/ioc"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitMiddleWares()
	db := ioc.InitDB()
	userDao := dao.NewUserDAO(db)
	userRepository := user_repo.NewUserRepository(userDao)
	userService := user_service.NewUserService(userRepository)
	userHandler := user_web.NewUserHandler(userService)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
